sudo: required
services:
  - docker

before_install:
  - docker build -t appcicd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run appcicd/react-test npm test -- --coverage

after_success:
  - docker build -t appcicd/fibcal-client ./client
  - docker build -t appcicd/fibcal-nginx ./nginx
  - docker build -t appcicd/fibcal-server ./server
  - docker build -t appcicd/fibcal-worker ./worker
 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push appcicd/fibcal-client
  - docker push appcicd/fibcal-nginx
  - docker push appcicd/fibcal-server
  - docker push appcicd/fibcal-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: fabcal
  env:  Fabcal-env
  bucket_name: "elasticbeanstalk-us-west-1-524167333514"
  bucket_path: fabcal
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY